print("Class:-")
print(class(Inf))
print(class(NA))
print(class(NaN))
print("type:-")
print(typeof(Inf))
print(typeof(NA))
print(typeof(NaN))
print("mode:-")
print(mode(Inf))
print(mode(NA))
print(mode(NaN))
print("Storage mode:-")
print(storage.mode(Inf))
print(storage.mode(NA))
print(storage.mode(NaN))